name: Build Image Using Docker Action

on: [push]

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run commands
        run: |
          uname -a
          arch
        
      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
          registry: quay.io

      - name: Build and Push Image
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: quay.io/siddhesh_ghadi/gha-demo:buildx-action
