name: Build Image Using Docker CLI

on: [push]

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run commands
        run: |
          uname -a
          arch
        
      - name: Login to Quay
        run: |
          echo ${{ secrets.QUAY_TOKEN }} | docker login quay.io -u ${{ secrets.QUAY_USERNAME }} --password-stdin

      - name: Build Image
        run: |
          docker build --tag quay.io/siddhesh_ghadi/gha-demo:buildx-cli .

      - name: Push Image
        run: |
          docker push quay.io/siddhesh_ghadi/gha-demo:buildx-cli

