name: Build Image Using Makefile

on: [push]

jobs:
  build:
    name: Build container image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login to Quay
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.QUAY_USERNAME }}
          password: ${{ secrets.QUAY_TOKEN }}
          registry: quay.io

      - name: Build & Push Image
        run: |
          export TAGS="quay.io/siddhesh_ghadi/gha-demo:makefile"
          make container
          make push
